name: neuronpyxl
channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.14
  - numpy>=2.1.2
  - pandas>=2.2.3
  - XlsxWriter>=3.2.0
  - openpyxl>=3.1.5
  - pytables>=3.10.1
  - scipy>=1.15.1
  - matplotlib
  - pip
  - pip:
    - ./
    - neuron==9.0.1; sys_platform != "win32"
