name: neuronpyxl-env
channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.13
  - numpy>=2.1.2
  - pandas>=2.2.3
  - XlsxWriter>=3.2.0
  - openpyxl>=3.1.5
  - pytables>=3.10.1
  - scipy>=1.15.1
  - pip
  - pip:
    - -e ./
    - neuron==8.2.7; sys_platform != "win32"