"""
Ex 2: Reading in data generated by NEURONpyxl CLI

First, generate the mod files by running:
    neuronpyxl -f gen_mods --file sheets/single_neuron2.xlsx
Run the simulation with:
      neuronpyxl -f run_sim --file sheets/single_neuron2.xlsx \
                            --name excitability --duration 9000 --method 3
Then run this file with:
    python examples/ex1.py
"""

import pandas as pd
import matplotlib.pyplot as plt

filepath = "data/excitability_data/excitability_data.h5" # Path to the data file
file = pd.HDFStore(filepath)                             # Read in the data file
keys = file.keys()
print(f"File {filepath} has keys: \
      {[k.replace("/","") for k in keys]}")              # Print keys in the data file

B4_data = file["B4"] # Get the data corresponding to the B4 neuron
print("B4 data")
print(B4_data) # View all data corresponding to the B4 neuron

# Plot the voltage data
t = B4_data["t"]/1000           # Convert to seconds
v = B4_data["V"]                # Get membrane potential
iapp = B4_data["I_app"]         # Get applied current

fig,axs = plt.subplots(2,1,figsize=(12,8),sharex=True)
axs[0].plot(t,v)
axs[0].set_ylabel("Voltage (mV)")

axs[1].plot(t,iapp)
axs[1].set_ylabel("Applied current (nA)")

fig.supxlabel("Time (s)")
fig.suptitle("Simple B4 Neuron Simulation")

plt.show()